namespace CivicConnect.Data.Entities;

/// An incident opened against a category and a location, with a priority computed from impact and urgency.
public sealed class Incident
{
    public long Id { get; set; }

    /// Identifier derived from the id (e.g. "INC-000001"); generated by the database.
    public string ReferenceNumber { get; set; } = null!;

    public int CategoryId { get; set; }
    public Category Category { get; set; } = null!;

    public int LocationId { get; set; }
    public Location Location { get; set; } = null!;

    public string Title { get; set; } = null!;
    public string Description { get; set; } = null!;

    public IncidentStatus Status { get; set; } = IncidentStatus.New;

    /// The priority computed from the location's impact level and the category's urgency level.
    public short ComputedPriority { get; set; }
    public PriorityTarget ComputedPriorityTarget { get; set; } = null!;

    /// The effective priority: equal to ComputedPriority unless a supervisor has overridden it.
    public short Priority { get; set; }
    public PriorityTarget PriorityTarget { get; set; } = null!;

    public bool PriorityOverridden { get; set; }
    public string? OverrideReason { get; set; }
    public Guid? OverrideBy { get; set; }
    public AppUser? OverrideByUser { get; set; }
    public DateTimeOffset? OverrideAt { get; set; }

    public long? MergedIntoId { get; set; }
    public Incident? MergedInto { get; set; }

    /// Incremented by the database on every update, so concurrent edits can be detected.
    public int Version { get; set; }

    public DateTimeOffset OpenedAt { get; set; }

    /// Derived by the database from the priority target's resolve-within-minutes value.
    public DateTimeOffset DueAt { get; set; }

    public DateTimeOffset? ResolvedAt { get; set; }
    public DateTimeOffset? ClosedAt { get; set; }
}
