namespace CivicConnect.Data.Entities;

/// One reporter's submission; carries its own reference number and attaches to one incident.
public sealed class Ticket
{
    public long Id { get; set; }

    /// Identifier derived from the id (e.g. "TKT-000001"); generated by the database, distinct from the incident's.
    public string ReferenceNumber { get; set; } = null!;

    public Guid ReporterId { get; set; }
    public AppUser Reporter { get; set; } = null!;

    public long IncidentId { get; set; }
    public Incident Incident { get; set; } = null!;

    public int CategoryId { get; set; }
    public Category Category { get; set; } = null!;

    public int LocationId { get; set; }
    public Location Location { get; set; } = null!;

    public string Title { get; set; } = null!;
    public string Description { get; set; } = null!;

    public DateTimeOffset SubmittedAt { get; set; }
}
