// <auto-generated />
using System;
using CivicConnect.Data;
using CivicConnect.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CivicConnect.Data.Migrations
{
    [DbContext(typeof(CivicConnectDbContext))]
    [Migration("20261010123743_AddNotesAndNotifications")]
    partial class AddNotesAndNotifications
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "incident_status", new[] { "NEW", "ASSIGNED", "IN_PROGRESS", "ON_HOLD", "RESOLVED", "CLOSED", "REJECTED", "MERGED" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "notification_kind", new[] { "STATUS_CHANGE", "ASSIGNMENT", "RESOLUTION" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CivicConnect.Data.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_app_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_app_user_email");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("asset_tag");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<DateOnly>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("supplier");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_asset");

                    b.HasIndex("AssetTag")
                        .IsUnique()
                        .HasDatabaseName("ix_asset_asset_tag");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_asset_location_id");

                    b.ToTable("asset", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("DefaultServiceTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("default_service_team_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("UrgencyLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("urgency_level");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("DefaultServiceTeamId")
                        .HasDatabaseName("ix_category_default_service_team_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("category_active_name_uq")
                        .HasFilter("is_active");

                    b.ToTable("category", null, t =>
                        {
                            t.HasCheckConstraint("category_urgency_level_range_ck", "urgency_level BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Incident", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AssignedTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_team_id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<short>("ComputedPriority")
                        .HasColumnType("smallint")
                        .HasColumnName("computed_priority");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DueAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<long?>("MergedIntoId")
                        .HasColumnType("bigint")
                        .HasColumnName("merged_into_id");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("OverrideAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("override_at");

                    b.Property<Guid?>("OverrideBy")
                        .HasColumnType("uuid")
                        .HasColumnName("override_by");

                    b.Property<string>("OverrideReason")
                        .HasColumnType("text")
                        .HasColumnName("override_reason");

                    b.Property<short>("Priority")
                        .HasColumnType("smallint")
                        .HasColumnName("priority");

                    b.Property<bool>("PriorityOverridden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("priority_overridden");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("reference_number")
                        .HasComputedColumnSql("'INC-' || lpad(id::text, 6, '0')", true);

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<IncidentStatus>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("incident_status")
                        .HasDefaultValue(IncidentStatus.New)
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_incident");

                    b.HasIndex("AssignedTeamId")
                        .HasDatabaseName("ix_incident_assigned_team_id");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_incident_assignee_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_incident_category_id");

                    b.HasIndex("ComputedPriority")
                        .HasDatabaseName("ix_incident_computed_priority");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_incident_location_id");

                    b.HasIndex("MergedIntoId")
                        .HasDatabaseName("ix_incident_merged_into_id");

                    b.HasIndex("OverrideBy")
                        .HasDatabaseName("ix_incident_override_by");

                    b.HasIndex("Priority")
                        .HasDatabaseName("ix_incident_priority");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_incident_reference_number");

                    b.ToTable("incident", null, t =>
                        {
                            t.HasCheckConstraint("incident_merge_not_self_ck", "id <> merged_into_id");

                            t.HasCheckConstraint("incident_override_ck", "(NOT priority_overridden\n                      AND override_reason IS NULL AND override_by IS NULL AND override_at IS NULL\n                      AND priority = computed_priority)\n                  OR (priority_overridden\n                      AND override_reason IS NOT NULL AND btrim(override_reason) <> ''\n                      AND override_by IS NOT NULL AND override_at IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.IncidentNote", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("IncidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("incident_id");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.HasKey("Id")
                        .HasName("pk_incident_note");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("ix_incident_note_author_id");

                    b.HasIndex("IncidentId", "CreatedAt")
                        .HasDatabaseName("ix_incident_note_incident_id_created_at");

                    b.ToTable("incident_note", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.IncidentStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AssignedTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("assigned_team_id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ChangedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("changed_by");

                    b.Property<IncidentStatus?>("FromStatus")
                        .HasColumnType("incident_status")
                        .HasColumnName("from_status");

                    b.Property<long>("IncidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("incident_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<IncidentStatus>("ToStatus")
                        .HasColumnType("incident_status")
                        .HasColumnName("to_status");

                    b.HasKey("Id")
                        .HasName("pk_incident_status_history");

                    b.HasIndex("AssignedTeamId")
                        .HasDatabaseName("ix_incident_status_history_assigned_team_id");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_incident_status_history_assignee_id");

                    b.HasIndex("ChangedBy")
                        .HasDatabaseName("ix_incident_status_history_changed_by");

                    b.HasIndex("IncidentId", "ChangedAt")
                        .HasDatabaseName("ix_incident_status_history_incident_id_changed_at");

                    b.ToTable("incident_status_history", null, t =>
                        {
                            t.HasCheckConstraint("incident_status_history_creation_ck", "from_status IS NOT NULL OR to_status = 'NEW'");
                        });
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.IncidentStatusTransition", b =>
                {
                    b.Property<IncidentStatus>("FromStatus")
                        .HasColumnType("incident_status")
                        .HasColumnName("from_status");

                    b.Property<IncidentStatus>("ToStatus")
                        .HasColumnType("incident_status")
                        .HasColumnName("to_status");

                    b.HasKey("FromStatus", "ToStatus")
                        .HasName("pk_incident_status_transition");

                    b.ToTable("incident_status_transition", (string)null);

                    b.HasData(
                        new
                        {
                            FromStatus = IncidentStatus.New,
                            ToStatus = IncidentStatus.Assigned
                        },
                        new
                        {
                            FromStatus = IncidentStatus.New,
                            ToStatus = IncidentStatus.Rejected
                        },
                        new
                        {
                            FromStatus = IncidentStatus.New,
                            ToStatus = IncidentStatus.Merged
                        },
                        new
                        {
                            FromStatus = IncidentStatus.Assigned,
                            ToStatus = IncidentStatus.InProgress
                        },
                        new
                        {
                            FromStatus = IncidentStatus.Assigned,
                            ToStatus = IncidentStatus.OnHold
                        },
                        new
                        {
                            FromStatus = IncidentStatus.Assigned,
                            ToStatus = IncidentStatus.Rejected
                        },
                        new
                        {
                            FromStatus = IncidentStatus.Assigned,
                            ToStatus = IncidentStatus.Merged
                        },
                        new
                        {
                            FromStatus = IncidentStatus.InProgress,
                            ToStatus = IncidentStatus.OnHold
                        },
                        new
                        {
                            FromStatus = IncidentStatus.InProgress,
                            ToStatus = IncidentStatus.Resolved
                        },
                        new
                        {
                            FromStatus = IncidentStatus.InProgress,
                            ToStatus = IncidentStatus.Merged
                        },
                        new
                        {
                            FromStatus = IncidentStatus.OnHold,
                            ToStatus = IncidentStatus.InProgress
                        },
                        new
                        {
                            FromStatus = IncidentStatus.OnHold,
                            ToStatus = IncidentStatus.Resolved
                        },
                        new
                        {
                            FromStatus = IncidentStatus.OnHold,
                            ToStatus = IncidentStatus.Merged
                        },
                        new
                        {
                            FromStatus = IncidentStatus.Resolved,
                            ToStatus = IncidentStatus.Closed
                        },
                        new
                        {
                            FromStatus = IncidentStatus.Resolved,
                            ToStatus = IncidentStatus.InProgress
                        });
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.IncidentSubscription", b =>
                {
                    b.Property<long>("IncidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("incident_id");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<DateTimeOffset>("SubscribedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("subscribed_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("IncidentId", "ReporterId")
                        .HasName("pk_incident_subscription");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_incident_subscription_reporter_id");

                    b.ToTable("incident_subscription", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<short>("ImpactLevel")
                        .HasColumnType("smallint")
                        .HasColumnName("impact_level");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<short>("LocationKindId")
                        .HasColumnType("smallint")
                        .HasColumnName("location_kind_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_location_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_location");

                    b.HasIndex("LocationKindId")
                        .HasDatabaseName("ix_location_location_kind_id");

                    b.HasIndex("ParentLocationId")
                        .HasDatabaseName("ix_location_parent_location_id");

                    b.ToTable("location", null, t =>
                        {
                            t.HasCheckConstraint("location_impact_level_range_ck", "impact_level BETWEEN 1 AND 4");

                            t.HasCheckConstraint("location_parent_not_self_ck", "id <> parent_location_id");
                        });
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.LocationKind", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_location_kind");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_location_kind_name");

                    b.ToTable("location_kind", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "site"
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "floor"
                        },
                        new
                        {
                            Id = (short)3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "room"
                        });
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dedup_key");

                    b.Property<long>("IncidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("incident_id");

                    b.Property<NotificationKind>("Kind")
                        .HasColumnType("notification_kind")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("read_at");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasDatabaseName("notification_dedup_key_uq");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_notification_incident_id");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_notification_recipient_unread")
                        .HasFilter("read_at IS NULL");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.PriorityTarget", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ResolveWithinMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("resolve_within_minutes");

                    b.HasKey("Id")
                        .HasName("pk_priority_target");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_priority_target_name");

                    b.ToTable("priority_target", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "critical",
                            ResolveWithinMinutes = 60
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "high",
                            ResolveWithinMinutes = 240
                        },
                        new
                        {
                            Id = (short)3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "medium",
                            ResolveWithinMinutes = 1440
                        },
                        new
                        {
                            Id = (short)4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "low",
                            ResolveWithinMinutes = 4320
                        });
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Resolution", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("AssetId")
                        .HasColumnType("integer")
                        .HasColumnName("asset_id");

                    b.Property<long>("IncidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("incident_id");

                    b.Property<bool>("NeedsReplacement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("needs_replacement");

                    b.Property<short>("ResolutionCodeId")
                        .HasColumnType("smallint")
                        .HasColumnName("resolution_code_id");

                    b.Property<DateTimeOffset>("ResolvedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset?>("SupersededAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("superseded_at");

                    b.HasKey("Id")
                        .HasName("pk_resolution");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_resolution_asset_id");

                    b.HasIndex("IncidentId")
                        .IsUnique()
                        .HasDatabaseName("resolution_incident_active_uq")
                        .HasFilter("superseded_at IS NULL");

                    b.HasIndex("ResolutionCodeId")
                        .HasDatabaseName("ix_resolution_resolution_code_id");

                    b.HasIndex("ResolvedBy")
                        .HasDatabaseName("ix_resolution_resolved_by");

                    b.HasIndex("IncidentId", "ResolvedAt")
                        .HasDatabaseName("ix_resolution_incident_id_resolved_at");

                    b.ToTable("resolution", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.ResolutionCode", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("ImpliesReplacement")
                        .HasColumnType("boolean")
                        .HasColumnName("implies_replacement");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_resolution_code");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_resolution_code_code");

                    b.ToTable("resolution_code", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Code = "FIXED",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ImpliesReplacement = false,
                            IsActive = true,
                            Name = "Fixed on site"
                        },
                        new
                        {
                            Id = (short)2,
                            Code = "NO_FAULT_FOUND",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ImpliesReplacement = false,
                            IsActive = true,
                            Name = "No fault found"
                        },
                        new
                        {
                            Id = (short)3,
                            Code = "DUPLICATE",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ImpliesReplacement = false,
                            IsActive = true,
                            Name = "Duplicate of another incident"
                        },
                        new
                        {
                            Id = (short)4,
                            Code = "HARDWARE_REPLACED",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ImpliesReplacement = true,
                            IsActive = true,
                            Name = "Faulty hardware replaced"
                        },
                        new
                        {
                            Id = (short)5,
                            Code = "BEYOND_REPAIR",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ImpliesReplacement = true,
                            IsActive = true,
                            Name = "Beyond repair, replacement required"
                        });
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Role", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_role_name");

                    b.ToTable("role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "reporter"
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "technician"
                        },
                        new
                        {
                            Id = (short)3,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "supervisor"
                        },
                        new
                        {
                            Id = (short)4,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "operations manager"
                        },
                        new
                        {
                            Id = (short)5,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "administrator"
                        });
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.ServiceTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_service_team");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_service_team_name");

                    b.ToTable("service_team", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.SubmissionRequest", b =>
                {
                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<string>("IdempotencyKey")
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_fingerprint");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_id");

                    b.HasKey("ReporterId", "IdempotencyKey")
                        .HasName("pk_submission_request");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_submission_request_expires_at");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_submission_request_ticket_id");

                    b.ToTable("submission_request", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.TeamMember", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("LeftAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("left_at");

                    b.Property<int>("ServiceTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("service_team_id");

                    b.Property<short>("TeamRoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("team_role_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_team_member");

                    b.HasIndex("ServiceTeamId")
                        .HasDatabaseName("ix_team_member_service_team_id");

                    b.HasIndex("TeamRoleId")
                        .HasDatabaseName("ix_team_member_team_role_id");

                    b.HasIndex("UserId", "ServiceTeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_member_user_id_service_team_id")
                        .HasFilter("left_at IS NULL");

                    b.ToTable("team_member", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.TeamRole", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_team_role");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_team_role_name");

                    b.ToTable("team_role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "technician"
                        },
                        new
                        {
                            Id = (short)2,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 9, 27, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Name = "supervisor"
                        });
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("IncidentId")
                        .HasColumnType("bigint")
                        .HasColumnName("incident_id");

                    b.Property<int>("LocationId")
                        .HasColumnType("integer")
                        .HasColumnName("location_id");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("reference_number")
                        .HasComputedColumnSql("'TKT-' || lpad(id::text, 6, '0')", true);

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_ticket");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_ticket_category_id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_ticket_incident_id");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_ticket_location_id");

                    b.HasIndex("ReferenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_reference_number");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_ticket_reporter_id");

                    b.ToTable("ticket", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<short>("RoleId")
                        .HasColumnType("smallint")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("granted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("GrantedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("granted_by_user_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_role");

                    b.HasIndex("GrantedByUserId")
                        .HasDatabaseName("ix_user_role_granted_by_user_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_role_role_id");

                    b.ToTable("user_role", (string)null);
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Asset", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.Location", "Location")
                        .WithMany("Assets")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_asset_locations_location_id");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Category", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.ServiceTeam", "DefaultServiceTeam")
                        .WithMany("DefaultCategories")
                        .HasForeignKey("DefaultServiceTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_category_service_teams_default_service_team_id");

                    b.Navigation("DefaultServiceTeam");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Incident", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.ServiceTeam", "AssignedTeam")
                        .WithMany()
                        .HasForeignKey("AssignedTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incident_service_teams_assigned_team_id");

                    b.HasOne("CivicConnect.Data.Entities.AppUser", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incident_app_user_assignee_id");

                    b.HasOne("CivicConnect.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_category_category_id");

                    b.HasOne("CivicConnect.Data.Entities.PriorityTarget", "ComputedPriorityTarget")
                        .WithMany()
                        .HasForeignKey("ComputedPriority")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_priority_targets_computed_priority");

                    b.HasOne("CivicConnect.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_locations_location_id");

                    b.HasOne("CivicConnect.Data.Entities.Incident", "MergedInto")
                        .WithMany()
                        .HasForeignKey("MergedIntoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incident_incident_merged_into_id");

                    b.HasOne("CivicConnect.Data.Entities.AppUser", "OverrideByUser")
                        .WithMany()
                        .HasForeignKey("OverrideBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incident_app_user_override_by");

                    b.HasOne("CivicConnect.Data.Entities.PriorityTarget", "PriorityTarget")
                        .WithMany()
                        .HasForeignKey("Priority")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_priority_targets_priority");

                    b.Navigation("AssignedTeam");

                    b.Navigation("Assignee");

                    b.Navigation("Category");

                    b.Navigation("ComputedPriorityTarget");

                    b.Navigation("Location");

                    b.Navigation("MergedInto");

                    b.Navigation("OverrideByUser");

                    b.Navigation("PriorityTarget");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.IncidentNote", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.AppUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_note_app_user_author_id");

                    b.HasOne("CivicConnect.Data.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_note_incident_incident_id");

                    b.Navigation("Author");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.IncidentStatusHistory", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.ServiceTeam", "AssignedTeam")
                        .WithMany()
                        .HasForeignKey("AssignedTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incident_status_history_service_teams_assigned_team_id");

                    b.HasOne("CivicConnect.Data.Entities.AppUser", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_incident_status_history_app_user_assignee_id");

                    b.HasOne("CivicConnect.Data.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_status_history_app_user_changed_by");

                    b.HasOne("CivicConnect.Data.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_status_history_incident_incident_id");

                    b.Navigation("AssignedTeam");

                    b.Navigation("Assignee");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.IncidentSubscription", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_subscription_incident_incident_id");

                    b.HasOne("CivicConnect.Data.Entities.AppUser", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_subscription_app_user_reporter_id");

                    b.Navigation("Incident");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Location", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.LocationKind", "LocationKind")
                        .WithMany("Locations")
                        .HasForeignKey("LocationKindId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_location_location_kinds_location_kind_id");

                    b.HasOne("CivicConnect.Data.Entities.Location", "ParentLocation")
                        .WithMany("ChildLocations")
                        .HasForeignKey("ParentLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_location_location_parent_location_id");

                    b.Navigation("LocationKind");

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Notification", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_incident_incident_id");

                    b.HasOne("CivicConnect.Data.Entities.AppUser", "Recipient")
                        .WithMany()
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_app_user_recipient_id");

                    b.Navigation("Incident");

                    b.Navigation("Recipient");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Resolution", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_resolution_asset_asset_id");

                    b.HasOne("CivicConnect.Data.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resolution_incident_incident_id");

                    b.HasOne("CivicConnect.Data.Entities.ResolutionCode", "ResolutionCode")
                        .WithMany()
                        .HasForeignKey("ResolutionCodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resolution_resolution_code_resolution_code_id");

                    b.HasOne("CivicConnect.Data.Entities.AppUser", "ResolvedByUser")
                        .WithMany()
                        .HasForeignKey("ResolvedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_resolution_app_user_resolved_by");

                    b.Navigation("Asset");

                    b.Navigation("Incident");

                    b.Navigation("ResolutionCode");

                    b.Navigation("ResolvedByUser");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.SubmissionRequest", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.AppUser", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_request_app_user_reporter_id");

                    b.HasOne("CivicConnect.Data.Entities.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_submission_request_tickets_ticket_id");

                    b.Navigation("Reporter");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.TeamMember", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.ServiceTeam", "ServiceTeam")
                        .WithMany("Members")
                        .HasForeignKey("ServiceTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_member_service_team_service_team_id");

                    b.HasOne("CivicConnect.Data.Entities.TeamRole", "TeamRole")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_member_team_roles_team_role_id");

                    b.HasOne("CivicConnect.Data.Entities.AppUser", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_member_app_user_user_id");

                    b.Navigation("ServiceTeam");

                    b.Navigation("TeamRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Ticket", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_category_category_id");

                    b.HasOne("CivicConnect.Data.Entities.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_incident_incident_id");

                    b.HasOne("CivicConnect.Data.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_location_location_id");

                    b.HasOne("CivicConnect.Data.Entities.AppUser", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_app_user_reporter_id");

                    b.Navigation("Category");

                    b.Navigation("Incident");

                    b.Navigation("Location");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.UserRole", b =>
                {
                    b.HasOne("CivicConnect.Data.Entities.AppUser", "GrantedByUser")
                        .WithMany()
                        .HasForeignKey("GrantedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_app_user_granted_by_user_id");

                    b.HasOne("CivicConnect.Data.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_role_role_id");

                    b.HasOne("CivicConnect.Data.Entities.AppUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_user_role_app_user_user_id");

                    b.Navigation("GrantedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.AppUser", b =>
                {
                    b.Navigation("TeamMemberships");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Location", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ChildLocations");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.LocationKind", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.ServiceTeam", b =>
                {
                    b.Navigation("DefaultCategories");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("CivicConnect.Data.Entities.TeamRole", b =>
                {
                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
